name: CMS Consistency Check Docker Image CI

on:
  push:
    tags:
      - 'release-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get tag name
        id: tagname
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"
        
      - name: Login to CERN Harbour
        uses: docker/login-action@v3
        with:
          registry: registry.cern.ch
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Build the Docker Image
        run: |
          cd docker && docker build . \
          --tag registry.cern.ch/${{ vars.HARBOR_REPOSITORY }}/rucio-consistency:${{ env.tag }}
      
      - name: Push Image to CERN Harbour
        run: docker push registry.cern.ch/${{ vars.HARBOR_REPOSITORY }}/rucio-consistency:${{ env.tag }}
  propagate-tag:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        repository: dmwm/rucio-flux
        token: ${{ secrets.CROSS_REPO_TOKEN }}
        path: rucio-flux

    - name: Create branch
      run: |
        cd rucio-flux
        git checkout -b update-consistency-image-${{ env.tag }}

    - name: Update image tag
      run: |
        cd rucio-flux
        sed -i "s|^tag:.*|tag: ${{ env.tag }}|" apps/production/prod-consistency.yaml

    - name: Commit changes
      run: |
        cd rucio-flux
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git commit -am "Update consistency image tag to ${{ env.tag }}"

    - name: Push branch
      run: |
        cd rucio-flux
        git push origin update-consistency-image-${{ env.tag }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.CROSS_REPO_TOKEN }}
        path: rucio-flux
        branch: update-consistency-image-${{ env.tag }}
        title: "Update consistency image tag to ${{ env.tag }}"
        body: |
          Automated PR updating Docker consistency image tag to `${{ env.tag }}`.
          See latest changes in https://github.com/dmwm/cms_consistency.
        base: main
